//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.gsccca.efile.accountservice
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://efile.gsccca.org/ucc", ConfigurationName="org.gsccca.efile.accountservice.AccountServiceSoap")]
    public interface AccountServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/CheckCredentials", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.accountservice.CheckCredentialsResponse> CheckCredentialsAsync(org.gsccca.efile.accountservice.CheckCredentialsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/QueryFunds", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.accountservice.QueryFundsResponse> QueryFundsAsync(org.gsccca.efile.accountservice.QueryFundsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/DepositDrawdownFunds", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.accountservice.DepositDrawdownFundsResponse> DepositDrawdownFundsAsync(org.gsccca.efile.accountservice.DepositDrawdownFundsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckCredentialsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckCredentials", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.accountservice.CheckCredentialsRequestBody Body;
        
        public CheckCredentialsRequest()
        {
        }
        
        public CheckCredentialsRequest(org.gsccca.efile.accountservice.CheckCredentialsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class CheckCredentialsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CheckCredentialsRequestBody()
        {
        }
        
        public CheckCredentialsRequestBody(string user, string password)
        {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckCredentialsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckCredentialsResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.accountservice.CheckCredentialsResponseBody Body;
        
        public CheckCredentialsResponse()
        {
        }
        
        public CheckCredentialsResponse(org.gsccca.efile.accountservice.CheckCredentialsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class CheckCredentialsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckCredentialsResult;
        
        public CheckCredentialsResponseBody()
        {
        }
        
        public CheckCredentialsResponseBody(bool CheckCredentialsResult)
        {
            this.CheckCredentialsResult = CheckCredentialsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryFundsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryFunds", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.accountservice.QueryFundsRequestBody Body;
        
        public QueryFundsRequest()
        {
        }
        
        public QueryFundsRequest(org.gsccca.efile.accountservice.QueryFundsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class QueryFundsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public QueryFundsRequestBody()
        {
        }
        
        public QueryFundsRequestBody(string user, string password)
        {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryFundsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryFundsResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.accountservice.QueryFundsResponseBody Body;
        
        public QueryFundsResponse()
        {
        }
        
        public QueryFundsResponse(org.gsccca.efile.accountservice.QueryFundsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class QueryFundsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QueryFundsResult;
        
        public QueryFundsResponseBody()
        {
        }
        
        public QueryFundsResponseBody(string QueryFundsResult)
        {
            this.QueryFundsResult = QueryFundsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepositDrawdownFundsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepositDrawdownFunds", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.accountservice.DepositDrawdownFundsRequestBody Body;
        
        public DepositDrawdownFundsRequest()
        {
        }
        
        public DepositDrawdownFundsRequest(org.gsccca.efile.accountservice.DepositDrawdownFundsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class DepositDrawdownFundsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal amount;
        
        public DepositDrawdownFundsRequestBody()
        {
        }
        
        public DepositDrawdownFundsRequestBody(string user, string password, string token, decimal amount)
        {
            this.user = user;
            this.password = password;
            this.token = token;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepositDrawdownFundsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepositDrawdownFundsResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.accountservice.DepositDrawdownFundsResponseBody Body;
        
        public DepositDrawdownFundsResponse()
        {
        }
        
        public DepositDrawdownFundsResponse(org.gsccca.efile.accountservice.DepositDrawdownFundsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class DepositDrawdownFundsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DepositDrawdownFundsResult;
        
        public DepositDrawdownFundsResponseBody()
        {
        }
        
        public DepositDrawdownFundsResponseBody(bool DepositDrawdownFundsResult)
        {
            this.DepositDrawdownFundsResult = DepositDrawdownFundsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public interface AccountServiceSoapChannel : org.gsccca.efile.accountservice.AccountServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public partial class AccountServiceSoapClient : System.ServiceModel.ClientBase<org.gsccca.efile.accountservice.AccountServiceSoap>, org.gsccca.efile.accountservice.AccountServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AccountServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AccountServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), AccountServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AccountServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AccountServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.accountservice.CheckCredentialsResponse> org.gsccca.efile.accountservice.AccountServiceSoap.CheckCredentialsAsync(org.gsccca.efile.accountservice.CheckCredentialsRequest request)
        {
            return base.Channel.CheckCredentialsAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.accountservice.CheckCredentialsResponse> CheckCredentialsAsync(string user, string password)
        {
            org.gsccca.efile.accountservice.CheckCredentialsRequest inValue = new org.gsccca.efile.accountservice.CheckCredentialsRequest();
            inValue.Body = new org.gsccca.efile.accountservice.CheckCredentialsRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            return ((org.gsccca.efile.accountservice.AccountServiceSoap)(this)).CheckCredentialsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.accountservice.QueryFundsResponse> org.gsccca.efile.accountservice.AccountServiceSoap.QueryFundsAsync(org.gsccca.efile.accountservice.QueryFundsRequest request)
        {
            return base.Channel.QueryFundsAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.accountservice.QueryFundsResponse> QueryFundsAsync(string user, string password)
        {
            org.gsccca.efile.accountservice.QueryFundsRequest inValue = new org.gsccca.efile.accountservice.QueryFundsRequest();
            inValue.Body = new org.gsccca.efile.accountservice.QueryFundsRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            return ((org.gsccca.efile.accountservice.AccountServiceSoap)(this)).QueryFundsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.accountservice.DepositDrawdownFundsResponse> org.gsccca.efile.accountservice.AccountServiceSoap.DepositDrawdownFundsAsync(org.gsccca.efile.accountservice.DepositDrawdownFundsRequest request)
        {
            return base.Channel.DepositDrawdownFundsAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.accountservice.DepositDrawdownFundsResponse> DepositDrawdownFundsAsync(string user, string password, string token, decimal amount)
        {
            org.gsccca.efile.accountservice.DepositDrawdownFundsRequest inValue = new org.gsccca.efile.accountservice.DepositDrawdownFundsRequest();
            inValue.Body = new org.gsccca.efile.accountservice.DepositDrawdownFundsRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.token = token;
            inValue.Body.amount = amount;
            return ((org.gsccca.efile.accountservice.AccountServiceSoap)(this)).DepositDrawdownFundsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccountServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AccountServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccountServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://efilestg.gsccca.org/efilewebservice/accountservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AccountServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://efilestg.gsccca.org/efilewebservice/accountservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AccountServiceSoap,
            
            AccountServiceSoap12,
        }
    }
}
