//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.gsccca.efile.uccservice
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://efile.gsccca.org/ucc", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://efile.gsccca.org/ucc", ConfigurationName="org.gsccca.efile.uccservice.UCCServiceSoap")]
    public interface UCCServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/IsParticipating", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.IsParticipatingResponse> IsParticipatingAsync(org.gsccca.efile.uccservice.IsParticipatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/Submit", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.SubmitResponse> SubmitAsync(org.gsccca.efile.uccservice.SubmitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/Resubmit", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.ResubmitResponse> ResubmitAsync(org.gsccca.efile.uccservice.ResubmitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/Pay", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.PayResponse> PayAsync(org.gsccca.efile.uccservice.PayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/Cancel", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.CancelResponse> CancelAsync(org.gsccca.efile.uccservice.CancelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetStatusResponse> GetStatusAsync(org.gsccca.efile.uccservice.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/ArchiveUCC", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.ArchiveUCCResponse> ArchiveUCCAsync(org.gsccca.efile.uccservice.ArchiveUCCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/GetFilingData", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetFilingDataResponse> GetFilingDataAsync(org.gsccca.efile.uccservice.GetFilingDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/GetFilingDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetFilingDocumentResponse> GetFilingDocumentAsync(org.gsccca.efile.uccservice.GetFilingDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/GetQueue", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetQueueResponse> GetQueueAsync(org.gsccca.efile.uccservice.GetQueueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/Accept", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.AcceptResponse> AcceptAsync(org.gsccca.efile.uccservice.AcceptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/AcceptSetDate", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.AcceptSetDateResponse> AcceptSetDateAsync(org.gsccca.efile.uccservice.AcceptSetDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/GetRejectionReasons", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetRejectionReasonsResponse> GetRejectionReasonsAsync(org.gsccca.efile.uccservice.GetRejectionReasonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/Reject", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.RejectResponse> RejectAsync(org.gsccca.efile.uccservice.RejectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/Unreject", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.UnrejectResponse> UnrejectAsync(org.gsccca.efile.uccservice.UnrejectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://efile.gsccca.org/ucc/CallbackExample", ReplyAction="*")]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.CallbackExampleResponse> CallbackExampleAsync(org.gsccca.efile.uccservice.CallbackExampleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsParticipatingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsParticipating", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.IsParticipatingRequestBody Body;
        
        public IsParticipatingRequest()
        {
        }
        
        public IsParticipatingRequest(org.gsccca.efile.uccservice.IsParticipatingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class IsParticipatingRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string county;
        
        public IsParticipatingRequestBody()
        {
        }
        
        public IsParticipatingRequestBody(string county)
        {
            this.county = county;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsParticipatingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsParticipatingResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.IsParticipatingResponseBody Body;
        
        public IsParticipatingResponse()
        {
        }
        
        public IsParticipatingResponse(org.gsccca.efile.uccservice.IsParticipatingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class IsParticipatingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsParticipatingResult;
        
        public IsParticipatingResponseBody()
        {
        }
        
        public IsParticipatingResponseBody(bool IsParticipatingResult)
        {
            this.IsParticipatingResult = IsParticipatingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Submit", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.SubmitRequestBody Body;
        
        public SubmitRequest()
        {
        }
        
        public SubmitRequest(org.gsccca.efile.uccservice.SubmitRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class SubmitRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string county;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string filingXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] document;
        
        public SubmitRequestBody()
        {
        }
        
        public SubmitRequestBody(string user, string pass, string county, string filingXML, byte[] document)
        {
            this.user = user;
            this.pass = pass;
            this.county = county;
            this.filingXML = filingXML;
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.SubmitResponseBody Body;
        
        public SubmitResponse()
        {
        }
        
        public SubmitResponse(org.gsccca.efile.uccservice.SubmitResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class SubmitResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitResult;
        
        public SubmitResponseBody()
        {
        }
        
        public SubmitResponseBody(string SubmitResult)
        {
            this.SubmitResult = SubmitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResubmitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Resubmit", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.ResubmitRequestBody Body;
        
        public ResubmitRequest()
        {
        }
        
        public ResubmitRequest(org.gsccca.efile.uccservice.ResubmitRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class ResubmitRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string county;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string filingXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] document;
        
        public ResubmitRequestBody()
        {
        }
        
        public ResubmitRequestBody(string user, string pass, string county, string filingXML, byte[] document)
        {
            this.user = user;
            this.pass = pass;
            this.county = county;
            this.filingXML = filingXML;
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResubmitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResubmitResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.ResubmitResponseBody Body;
        
        public ResubmitResponse()
        {
        }
        
        public ResubmitResponse(org.gsccca.efile.uccservice.ResubmitResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class ResubmitResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResubmitResult;
        
        public ResubmitResponseBody()
        {
        }
        
        public ResubmitResponseBody(string ResubmitResult)
        {
            this.ResubmitResult = ResubmitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Pay", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.PayRequestBody Body;
        
        public PayRequest()
        {
        }
        
        public PayRequest(org.gsccca.efile.uccservice.PayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class PayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal fee;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int id;
        
        public PayRequestBody()
        {
        }
        
        public PayRequestBody(string user, string pass, string token, decimal fee, int id)
        {
            this.user = user;
            this.pass = pass;
            this.token = token;
            this.fee = fee;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.PayResponseBody Body;
        
        public PayResponse()
        {
        }
        
        public PayResponse(org.gsccca.efile.uccservice.PayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class PayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PayResult;
        
        public PayResponseBody()
        {
        }
        
        public PayResponseBody(bool PayResult)
        {
            this.PayResult = PayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cancel", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.CancelRequestBody Body;
        
        public CancelRequest()
        {
        }
        
        public CancelRequest(org.gsccca.efile.uccservice.CancelRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class CancelRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        public CancelRequestBody()
        {
        }
        
        public CancelRequestBody(string user, string pass, int id)
        {
            this.user = user;
            this.pass = pass;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.CancelResponseBody Body;
        
        public CancelResponse()
        {
        }
        
        public CancelResponse(org.gsccca.efile.uccservice.CancelResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class CancelResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CancelResult;
        
        public CancelResponseBody()
        {
        }
        
        public CancelResponseBody(bool CancelResult)
        {
            this.CancelResult = CancelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.GetStatusRequestBody Body;
        
        public GetStatusRequest()
        {
        }
        
        public GetStatusRequest(org.gsccca.efile.uccservice.GetStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class GetStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        public GetStatusRequestBody()
        {
        }
        
        public GetStatusRequestBody(string user, string pass, int id)
        {
            this.user = user;
            this.pass = pass;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.GetStatusResponseBody Body;
        
        public GetStatusResponse()
        {
        }
        
        public GetStatusResponse(org.gsccca.efile.uccservice.GetStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class GetStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStatusResult;
        
        public GetStatusResponseBody()
        {
        }
        
        public GetStatusResponseBody(string GetStatusResult)
        {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ArchiveUCCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ArchiveUCC", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.ArchiveUCCRequestBody Body;
        
        public ArchiveUCCRequest()
        {
        }
        
        public ArchiveUCCRequest(org.gsccca.efile.uccservice.ArchiveUCCRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class ArchiveUCCRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        public ArchiveUCCRequestBody()
        {
        }
        
        public ArchiveUCCRequestBody(string user, string pass, int id)
        {
            this.user = user;
            this.pass = pass;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ArchiveUCCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ArchiveUCCResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.ArchiveUCCResponseBody Body;
        
        public ArchiveUCCResponse()
        {
        }
        
        public ArchiveUCCResponse(org.gsccca.efile.uccservice.ArchiveUCCResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class ArchiveUCCResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ArchiveUCCResult;
        
        public ArchiveUCCResponseBody()
        {
        }
        
        public ArchiveUCCResponseBody(bool ArchiveUCCResult)
        {
            this.ArchiveUCCResult = ArchiveUCCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingData", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.GetFilingDataRequestBody Body;
        
        public GetFilingDataRequest()
        {
        }
        
        public GetFilingDataRequest(org.gsccca.efile.uccservice.GetFilingDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class GetFilingDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        public GetFilingDataRequestBody()
        {
        }
        
        public GetFilingDataRequestBody(string user, string pass, int id)
        {
            this.user = user;
            this.pass = pass;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingDataResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.GetFilingDataResponseBody Body;
        
        public GetFilingDataResponse()
        {
        }
        
        public GetFilingDataResponse(org.gsccca.efile.uccservice.GetFilingDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class GetFilingDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFilingDataResult;
        
        public GetFilingDataResponseBody()
        {
        }
        
        public GetFilingDataResponseBody(string GetFilingDataResult)
        {
            this.GetFilingDataResult = GetFilingDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingDocument", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.GetFilingDocumentRequestBody Body;
        
        public GetFilingDocumentRequest()
        {
        }
        
        public GetFilingDocumentRequest(org.gsccca.efile.uccservice.GetFilingDocumentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class GetFilingDocumentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        public GetFilingDocumentRequestBody()
        {
        }
        
        public GetFilingDocumentRequestBody(string user, string pass, int id)
        {
            this.user = user;
            this.pass = pass;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilingDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilingDocumentResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.GetFilingDocumentResponseBody Body;
        
        public GetFilingDocumentResponse()
        {
        }
        
        public GetFilingDocumentResponse(org.gsccca.efile.uccservice.GetFilingDocumentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class GetFilingDocumentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFilingDocumentResult;
        
        public GetFilingDocumentResponseBody()
        {
        }
        
        public GetFilingDocumentResponseBody(byte[] GetFilingDocumentResult)
        {
            this.GetFilingDocumentResult = GetFilingDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueue", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.GetQueueRequestBody Body;
        
        public GetQueueRequest()
        {
        }
        
        public GetQueueRequest(org.gsccca.efile.uccservice.GetQueueRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class GetQueueRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public GetQueueRequestBody()
        {
        }
        
        public GetQueueRequestBody(string user, string pass)
        {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueueResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.GetQueueResponseBody Body;
        
        public GetQueueResponse()
        {
        }
        
        public GetQueueResponse(org.gsccca.efile.uccservice.GetQueueResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class GetQueueResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public org.gsccca.efile.uccservice.ArrayOfString GetQueueResult;
        
        public GetQueueResponseBody()
        {
        }
        
        public GetQueueResponseBody(org.gsccca.efile.uccservice.ArrayOfString GetQueueResult)
        {
            this.GetQueueResult = GetQueueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcceptRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Accept", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.AcceptRequestBody Body;
        
        public AcceptRequest()
        {
        }
        
        public AcceptRequest(org.gsccca.efile.uccservice.AcceptRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class AcceptRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string filenumber;
        
        public AcceptRequestBody()
        {
        }
        
        public AcceptRequestBody(string user, string pass, int id, string filenumber)
        {
            this.user = user;
            this.pass = pass;
            this.id = id;
            this.filenumber = filenumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcceptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcceptResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.AcceptResponseBody Body;
        
        public AcceptResponse()
        {
        }
        
        public AcceptResponse(org.gsccca.efile.uccservice.AcceptResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class AcceptResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AcceptResult;
        
        public AcceptResponseBody()
        {
        }
        
        public AcceptResponseBody(string AcceptResult)
        {
            this.AcceptResult = AcceptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcceptSetDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcceptSetDate", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.AcceptSetDateRequestBody Body;
        
        public AcceptSetDateRequest()
        {
        }
        
        public AcceptSetDateRequest(org.gsccca.efile.uccservice.AcceptSetDateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class AcceptSetDateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string filenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string datetime;
        
        public AcceptSetDateRequestBody()
        {
        }
        
        public AcceptSetDateRequestBody(string user, string pass, int id, string filenumber, string datetime)
        {
            this.user = user;
            this.pass = pass;
            this.id = id;
            this.filenumber = filenumber;
            this.datetime = datetime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcceptSetDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcceptSetDateResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.AcceptSetDateResponseBody Body;
        
        public AcceptSetDateResponse()
        {
        }
        
        public AcceptSetDateResponse(org.gsccca.efile.uccservice.AcceptSetDateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class AcceptSetDateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AcceptSetDateResult;
        
        public AcceptSetDateResponseBody()
        {
        }
        
        public AcceptSetDateResponseBody(string AcceptSetDateResult)
        {
            this.AcceptSetDateResult = AcceptSetDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRejectionReasonsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRejectionReasons", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.GetRejectionReasonsRequestBody Body;
        
        public GetRejectionReasonsRequest()
        {
        }
        
        public GetRejectionReasonsRequest(org.gsccca.efile.uccservice.GetRejectionReasonsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRejectionReasonsRequestBody
    {
        
        public GetRejectionReasonsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRejectionReasonsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRejectionReasonsResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.GetRejectionReasonsResponseBody Body;
        
        public GetRejectionReasonsResponse()
        {
        }
        
        public GetRejectionReasonsResponse(org.gsccca.efile.uccservice.GetRejectionReasonsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class GetRejectionReasonsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public org.gsccca.efile.uccservice.ArrayOfString GetRejectionReasonsResult;
        
        public GetRejectionReasonsResponseBody()
        {
        }
        
        public GetRejectionReasonsResponseBody(org.gsccca.efile.uccservice.ArrayOfString GetRejectionReasonsResult)
        {
            this.GetRejectionReasonsResult = GetRejectionReasonsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RejectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reject", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.RejectRequestBody Body;
        
        public RejectRequest()
        {
        }
        
        public RejectRequest(org.gsccca.efile.uccservice.RejectRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class RejectRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public org.gsccca.efile.uccservice.ArrayOfString reasons;
        
        public RejectRequestBody()
        {
        }
        
        public RejectRequestBody(string user, string pass, int id, org.gsccca.efile.uccservice.ArrayOfString reasons)
        {
            this.user = user;
            this.pass = pass;
            this.id = id;
            this.reasons = reasons;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RejectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RejectResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.RejectResponseBody Body;
        
        public RejectResponse()
        {
        }
        
        public RejectResponse(org.gsccca.efile.uccservice.RejectResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class RejectResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RejectResult;
        
        public RejectResponseBody()
        {
        }
        
        public RejectResponseBody(bool RejectResult)
        {
            this.RejectResult = RejectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnrejectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Unreject", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.UnrejectRequestBody Body;
        
        public UnrejectRequest()
        {
        }
        
        public UnrejectRequest(org.gsccca.efile.uccservice.UnrejectRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class UnrejectRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        public UnrejectRequestBody()
        {
        }
        
        public UnrejectRequestBody(string user, string pass, int id)
        {
            this.user = user;
            this.pass = pass;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnrejectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnrejectResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.UnrejectResponseBody Body;
        
        public UnrejectResponse()
        {
        }
        
        public UnrejectResponse(org.gsccca.efile.uccservice.UnrejectResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class UnrejectResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UnrejectResult;
        
        public UnrejectResponseBody()
        {
        }
        
        public UnrejectResponseBody(bool UnrejectResult)
        {
            this.UnrejectResult = UnrejectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallbackExampleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallbackExample", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.CallbackExampleRequestBody Body;
        
        public CallbackExampleRequest()
        {
        }
        
        public CallbackExampleRequest(org.gsccca.efile.uccservice.CallbackExampleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class CallbackExampleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string status;
        
        public CallbackExampleRequestBody()
        {
        }
        
        public CallbackExampleRequestBody(string token, string status)
        {
            this.token = token;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallbackExampleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallbackExampleResponse", Namespace="https://efile.gsccca.org/ucc", Order=0)]
        public org.gsccca.efile.uccservice.CallbackExampleResponseBody Body;
        
        public CallbackExampleResponse()
        {
        }
        
        public CallbackExampleResponse(org.gsccca.efile.uccservice.CallbackExampleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://efile.gsccca.org/ucc")]
    public partial class CallbackExampleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CallbackExampleResult;
        
        public CallbackExampleResponseBody()
        {
        }
        
        public CallbackExampleResponseBody(string CallbackExampleResult)
        {
            this.CallbackExampleResult = CallbackExampleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface UCCServiceSoapChannel : org.gsccca.efile.uccservice.UCCServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class UCCServiceSoapClient : System.ServiceModel.ClientBase<org.gsccca.efile.uccservice.UCCServiceSoap>, org.gsccca.efile.uccservice.UCCServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UCCServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(UCCServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), UCCServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UCCServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UCCServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UCCServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UCCServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UCCServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.IsParticipatingResponse> org.gsccca.efile.uccservice.UCCServiceSoap.IsParticipatingAsync(org.gsccca.efile.uccservice.IsParticipatingRequest request)
        {
            return base.Channel.IsParticipatingAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.IsParticipatingResponse> IsParticipatingAsync(string county)
        {
            org.gsccca.efile.uccservice.IsParticipatingRequest inValue = new org.gsccca.efile.uccservice.IsParticipatingRequest();
            inValue.Body = new org.gsccca.efile.uccservice.IsParticipatingRequestBody();
            inValue.Body.county = county;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).IsParticipatingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.SubmitResponse> org.gsccca.efile.uccservice.UCCServiceSoap.SubmitAsync(org.gsccca.efile.uccservice.SubmitRequest request)
        {
            return base.Channel.SubmitAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.SubmitResponse> SubmitAsync(string user, string pass, string county, string filingXML, byte[] document)
        {
            org.gsccca.efile.uccservice.SubmitRequest inValue = new org.gsccca.efile.uccservice.SubmitRequest();
            inValue.Body = new org.gsccca.efile.uccservice.SubmitRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.county = county;
            inValue.Body.filingXML = filingXML;
            inValue.Body.document = document;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).SubmitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.ResubmitResponse> org.gsccca.efile.uccservice.UCCServiceSoap.ResubmitAsync(org.gsccca.efile.uccservice.ResubmitRequest request)
        {
            return base.Channel.ResubmitAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.ResubmitResponse> ResubmitAsync(string user, string pass, string county, string filingXML, byte[] document)
        {
            org.gsccca.efile.uccservice.ResubmitRequest inValue = new org.gsccca.efile.uccservice.ResubmitRequest();
            inValue.Body = new org.gsccca.efile.uccservice.ResubmitRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.county = county;
            inValue.Body.filingXML = filingXML;
            inValue.Body.document = document;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).ResubmitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.PayResponse> org.gsccca.efile.uccservice.UCCServiceSoap.PayAsync(org.gsccca.efile.uccservice.PayRequest request)
        {
            return base.Channel.PayAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.PayResponse> PayAsync(string user, string pass, string token, decimal fee, int id)
        {
            org.gsccca.efile.uccservice.PayRequest inValue = new org.gsccca.efile.uccservice.PayRequest();
            inValue.Body = new org.gsccca.efile.uccservice.PayRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.token = token;
            inValue.Body.fee = fee;
            inValue.Body.id = id;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).PayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.CancelResponse> org.gsccca.efile.uccservice.UCCServiceSoap.CancelAsync(org.gsccca.efile.uccservice.CancelRequest request)
        {
            return base.Channel.CancelAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.CancelResponse> CancelAsync(string user, string pass, int id)
        {
            org.gsccca.efile.uccservice.CancelRequest inValue = new org.gsccca.efile.uccservice.CancelRequest();
            inValue.Body = new org.gsccca.efile.uccservice.CancelRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.id = id;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).CancelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetStatusResponse> org.gsccca.efile.uccservice.UCCServiceSoap.GetStatusAsync(org.gsccca.efile.uccservice.GetStatusRequest request)
        {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetStatusResponse> GetStatusAsync(string user, string pass, int id)
        {
            org.gsccca.efile.uccservice.GetStatusRequest inValue = new org.gsccca.efile.uccservice.GetStatusRequest();
            inValue.Body = new org.gsccca.efile.uccservice.GetStatusRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.id = id;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).GetStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.ArchiveUCCResponse> org.gsccca.efile.uccservice.UCCServiceSoap.ArchiveUCCAsync(org.gsccca.efile.uccservice.ArchiveUCCRequest request)
        {
            return base.Channel.ArchiveUCCAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.ArchiveUCCResponse> ArchiveUCCAsync(string user, string pass, int id)
        {
            org.gsccca.efile.uccservice.ArchiveUCCRequest inValue = new org.gsccca.efile.uccservice.ArchiveUCCRequest();
            inValue.Body = new org.gsccca.efile.uccservice.ArchiveUCCRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.id = id;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).ArchiveUCCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetFilingDataResponse> org.gsccca.efile.uccservice.UCCServiceSoap.GetFilingDataAsync(org.gsccca.efile.uccservice.GetFilingDataRequest request)
        {
            return base.Channel.GetFilingDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetFilingDataResponse> GetFilingDataAsync(string user, string pass, int id)
        {
            org.gsccca.efile.uccservice.GetFilingDataRequest inValue = new org.gsccca.efile.uccservice.GetFilingDataRequest();
            inValue.Body = new org.gsccca.efile.uccservice.GetFilingDataRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.id = id;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).GetFilingDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetFilingDocumentResponse> org.gsccca.efile.uccservice.UCCServiceSoap.GetFilingDocumentAsync(org.gsccca.efile.uccservice.GetFilingDocumentRequest request)
        {
            return base.Channel.GetFilingDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetFilingDocumentResponse> GetFilingDocumentAsync(string user, string pass, int id)
        {
            org.gsccca.efile.uccservice.GetFilingDocumentRequest inValue = new org.gsccca.efile.uccservice.GetFilingDocumentRequest();
            inValue.Body = new org.gsccca.efile.uccservice.GetFilingDocumentRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.id = id;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).GetFilingDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetQueueResponse> org.gsccca.efile.uccservice.UCCServiceSoap.GetQueueAsync(org.gsccca.efile.uccservice.GetQueueRequest request)
        {
            return base.Channel.GetQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetQueueResponse> GetQueueAsync(string user, string pass)
        {
            org.gsccca.efile.uccservice.GetQueueRequest inValue = new org.gsccca.efile.uccservice.GetQueueRequest();
            inValue.Body = new org.gsccca.efile.uccservice.GetQueueRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).GetQueueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.AcceptResponse> org.gsccca.efile.uccservice.UCCServiceSoap.AcceptAsync(org.gsccca.efile.uccservice.AcceptRequest request)
        {
            return base.Channel.AcceptAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.AcceptResponse> AcceptAsync(string user, string pass, int id, string filenumber)
        {
            org.gsccca.efile.uccservice.AcceptRequest inValue = new org.gsccca.efile.uccservice.AcceptRequest();
            inValue.Body = new org.gsccca.efile.uccservice.AcceptRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.id = id;
            inValue.Body.filenumber = filenumber;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).AcceptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.AcceptSetDateResponse> org.gsccca.efile.uccservice.UCCServiceSoap.AcceptSetDateAsync(org.gsccca.efile.uccservice.AcceptSetDateRequest request)
        {
            return base.Channel.AcceptSetDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.AcceptSetDateResponse> AcceptSetDateAsync(string user, string pass, int id, string filenumber, string datetime)
        {
            org.gsccca.efile.uccservice.AcceptSetDateRequest inValue = new org.gsccca.efile.uccservice.AcceptSetDateRequest();
            inValue.Body = new org.gsccca.efile.uccservice.AcceptSetDateRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.id = id;
            inValue.Body.filenumber = filenumber;
            inValue.Body.datetime = datetime;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).AcceptSetDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetRejectionReasonsResponse> org.gsccca.efile.uccservice.UCCServiceSoap.GetRejectionReasonsAsync(org.gsccca.efile.uccservice.GetRejectionReasonsRequest request)
        {
            return base.Channel.GetRejectionReasonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.GetRejectionReasonsResponse> GetRejectionReasonsAsync()
        {
            org.gsccca.efile.uccservice.GetRejectionReasonsRequest inValue = new org.gsccca.efile.uccservice.GetRejectionReasonsRequest();
            inValue.Body = new org.gsccca.efile.uccservice.GetRejectionReasonsRequestBody();
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).GetRejectionReasonsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.RejectResponse> org.gsccca.efile.uccservice.UCCServiceSoap.RejectAsync(org.gsccca.efile.uccservice.RejectRequest request)
        {
            return base.Channel.RejectAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.RejectResponse> RejectAsync(string user, string pass, int id, org.gsccca.efile.uccservice.ArrayOfString reasons)
        {
            org.gsccca.efile.uccservice.RejectRequest inValue = new org.gsccca.efile.uccservice.RejectRequest();
            inValue.Body = new org.gsccca.efile.uccservice.RejectRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.id = id;
            inValue.Body.reasons = reasons;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).RejectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.UnrejectResponse> org.gsccca.efile.uccservice.UCCServiceSoap.UnrejectAsync(org.gsccca.efile.uccservice.UnrejectRequest request)
        {
            return base.Channel.UnrejectAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.UnrejectResponse> UnrejectAsync(string user, string pass, int id)
        {
            org.gsccca.efile.uccservice.UnrejectRequest inValue = new org.gsccca.efile.uccservice.UnrejectRequest();
            inValue.Body = new org.gsccca.efile.uccservice.UnrejectRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.id = id;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).UnrejectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<org.gsccca.efile.uccservice.CallbackExampleResponse> org.gsccca.efile.uccservice.UCCServiceSoap.CallbackExampleAsync(org.gsccca.efile.uccservice.CallbackExampleRequest request)
        {
            return base.Channel.CallbackExampleAsync(request);
        }
        
        public System.Threading.Tasks.Task<org.gsccca.efile.uccservice.CallbackExampleResponse> CallbackExampleAsync(string token, string status)
        {
            org.gsccca.efile.uccservice.CallbackExampleRequest inValue = new org.gsccca.efile.uccservice.CallbackExampleRequest();
            inValue.Body = new org.gsccca.efile.uccservice.CallbackExampleRequestBody();
            inValue.Body.token = token;
            inValue.Body.status = status;
            return ((org.gsccca.efile.uccservice.UCCServiceSoap)(this)).CallbackExampleAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UCCServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.UCCServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UCCServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://efilestg.gsccca.org/eFileWebService/UCCService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.UCCServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://efilestg.gsccca.org/eFileWebService/UCCService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            UCCServiceSoap,
            
            UCCServiceSoap12,
        }
    }
}
